services:
  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./service/observability/tempo.yaml/config.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"   # Tempo HTTP API (query)
      - "4318:4318"   # OTLP HTTP
      - "4317:4317"   # OTLP gRPC
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./service/observability/grafana-datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - tempo
    restart: unless-stopped

# Start:  docker compose -f docker-compose.tracing.yml up -d
# Stop:   docker compose -f docker-compose.tracing.yml down
# Grafana: http://localhost:3000  (admin / admin)
# Tempo OTLP: HTTP http://localhost:4318  | gRPC http://localhost:4317