apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-go
  labels:
    app: practice-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice-go
  template:
    metadata:
      labels:
        app: practice-go
    spec:
      containers:
      - name: practice-go
        image: practice-go:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: practice-go-config
        - secretRef:
            name: practice-go-secret
        # Readiness probe - kiểm tra xem pod đã sẵn sàng nhận traffic chưa
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        # Liveness probe - kiểm tra xem pod còn sống không
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
