apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sh: |
    #!/bin/bash
    # Wait for postgres to be ready
    until pg_isready -U postgres; do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done
    
    # Create database if not exists
    psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'practice_go'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE practice_go"
    
    echo "PostgreSQL initialized successfully"
