apiVersion: v1
kind: Service
metadata:
  name: practice-go
  namespace: practice-go-local
  labels:
    app: practice-go
    service: practice-go
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: practice-go